name: Tharun workflow
on: push

jobs: 
    tharun_job:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: Install cowsay program
          run: sudo apt-get install cowsay -y

        
        - name: execute cowsay cmd
          run: cowsay -f elephant  "tharun loves hemanth" >> dragon.txt

        - name: test file exists
          run: grep -i "elephant" dragon.txt
        - name: Read file
          run: cat dragon.txt

        - name: Listing all files in this
          run:  ls -ltra
           
          