name: vikram-job
on:
  workflow_dispatch: 
jobs:
  fuck_you:
    runs-on: ubuntu-latest
    steps:
     - name: Install cowsay
       run: sudo apt-get install cowsay -y
     - name:  Execute cowsay cmd
       run: cowsay -f dragon "Tharun dragon lafoot ga" >>dragon.txt
     - name: uplading artifact
       uses: actions/upload-artifact@v4
       with:
         name: my-artifact
         path: dragon.txt
       
  neabba:
    needs: fuck_you
    runs-on: ubuntu-latest
    steps:
     - name: sleep for 10 seconds
       run: sleep 10
     - name: download artifact
       uses: actions/download-artifact@v4
       with:
          name: my-artifact
        
     - name: test file
       run: grep -i "dragon" dragon.txt

  tharun-kattappa:
    needs: [neabba,fuck_you]
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
         name: my-artifact
      - name: read the file
        run: cat  dragon.txt
    
        
